[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[build]
  command = "npm run build && cp -r .svelte-kit/output/prerendered build"
  publish = "build"